# Generated by Django 3.1.2 on 2020-12-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryMOdel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField(unique=True)),
                ('Email_id', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('Date_of_join', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMOdel',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('Education', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='user_image/')),
                ('resume', models.FileField(upload_to='user_resume/')),
                ('itype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.industrymodel')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='process.registrationmodel')),
            ],
        ),
    ]
