# Generated by Django 3.1.2 on 2020-12-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_registrationmodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
